spring:
  profiles:
    active: dev
  thymeleaf:
     mode: HTML5
     cache: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://115.159.148.70:3306/work?characterEncoding=utf8&useSSL=true
    username: root
    password: 961017


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

<<<<<<< HEAD
server:
    port: 8085

mybatis:
   config-location: classpath:/mybatis-config.xml

logging:
  level:
    org.springfromework.web: info
