spring:
  profiles:
    active: dev
  thymeleaf:
     mode: HTML5
     cache: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://115.159.148.70:3306/test?characterEncoding=utf8&useSSL=true
    username: root
    password: 961017

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  server:
    port: 8085