spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://115.159.148.70:3306/test?characterEncoding=utf8&useSSL=true
    username: root
    password: 961017

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    cache: false

server:
  port: 8083

logging:
  level:
    org.springfromework.web: info